### ISSUE TITLE
[7.0.1] open directory if search result is a directory

### ISSUE THREAD

**Issue by ferdiga** [owncloud/search_lucene#35] opened 2014-08-12 12:22 UTC
Klicking on a search result which is a directory should open THIS directory not it's parent.

![image](https://cloud.githubusercontent.com/assets/6248560/3890184/48bd0dce-221b-11e4-8689-38fd58cfb432.png)

**Comment by VicDeo** [comment] 2015-04-13 21:16
Not related to fulltext search. (And fixed in master)

**Closed by VicDeo** 2015-04-13 21:16 UTC

**Comment by VicDeo** [comment] 2015-04-13 22:11
Closed as a duplicate of https://github.com/owncloud/core/issues/11353
