### ISSUE TITLE
Search results only found in .pdf and .odt files

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/search_lucene#55] opened 2015-01-29 11:09 UTC
Original reported in https://github.com/owncloud/core/issues/13685 by  @jnfrmarks 

### Steps to reproduce

1. Install owncloud
2. Upload a .txt file that contains the word owncloud (or, create one locally)
3. Upload a pdf file that contains the word owncloud
4. upload a doc/docx file that contains the word owncloud
5. upload an xlsx file that contains the word owncloud
6. upload an odt file that contains the work owncloud
7. enter owncloud in the search box

### Expected behaviour

Expect results to contain all files

### Actual behaviour

Results contain only odt and pdf files

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 2 (testing)

**Comment by karlitschek** [comment] 2015-01-29 13:56
@butonic

**Comment by butonic** [comment] 2015-01-29 20:38
@nickvergessen Did the cronjob have time to run? Files are indexed in the background and will eventually becoma available in the search results.

**Comment by nickvergessen** [comment] 2015-01-29 21:50
@butonic I have no idea, @jnfrmarks reported it, I just moved the issue to the correct repo

**Comment by butonic** [comment] 2015-02-04 09:38
closing, see https://github.com/owncloud/core/issues/13687#issuecomment-72069043

**Comment by VicDeo** [comment] 2015-04-01 22:53
Can't reproduce for master. After a short time that is required to index the file content, it appears in the search results

**Comment by VicDeo** [comment] 2015-04-01 23:02
@jnfrmarks core doesn't search by content but search_lucene does. It is not clear from initial issue (https://github.com/owncloud/core/issues/13685), whether you have this app enabled. Content should be indexed by a cron job

**Comment by cmonteroluque** [comment] 2015-06-25 21:27
@jnfrmarks @VicDeo I'd love to clean this out. Is @VicDeo's comment sufficient to close this?

**Comment by jnfrmarks** [comment] 2015-06-26 14:28
Yes; this looks really to be a dup of what was in core.

**Closed by jnfrmarks** 2015-06-26 14:28 UTC
Labels: bug, needs info
