### ISSUE TITLE
Old files aren't removed from search index

### ISSUE THREAD

**Issue by resound88** [owncloud/search_lucene#70] opened 2015-03-20 12:13 UTC
Hi together,

accidentally I noticed, that old files aren't immediately removed from the search index, after they get deleted.
A run of the cronjob doesn't change anything.

I'm not sure if this is a known limitation or a bug.

I can reproduce it on Debian 6.
Meanwhile I use version OC version 8.0.2.

Best regards

**Comment by karlitschek** [comment] 2015-03-20 13:58
@butonic any idea?

**Comment by butonic** [comment] 2015-03-26 14:15
With oc8 we moved to a background job that cleans up deleted files in the status table. It runs every 10min and decouples the delete from file operations which speeds up sync performance on deletes. For search this time limited inconsistency between files and index (or search results) is considered acceptable.

Closing as this works as designed.

@resound88 Can you verify that your deleted files meanwhile no longer show up in the search results? If they do, please reopen.

**Comment by resound88** [comment] 2015-03-27 07:54
@butonic Not even after 12 hours the search index is refreshed on our instance. What information do you need for further investigation?

**Comment by butonic** [comment] 2015-03-27 08:46
Looking at the code, this seems to be a side effect of https://github.com/owncloud/search_lucene/issues/49. Following up there.

**Closed** 2016-10-11 15:41 UTC
Labels: bug
